export const dynamic = 'force-dynamic';

import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

export async function GET() {
  const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  );

  try {
    const { data, error } = await supabase
      .from('v_deposits_summary')
      .select('*')
      .order('created_at', { ascending: false });

    if (error) throw error;

    return NextResponse.json(data || []);
  } catch (err: any) {
    console.error('GET DEPOSITS ERROR:', err);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}

export async function POST(request: Request) {
  const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  );

  try {
    const body = await request.json();
    
    const {
      customer_id,
      price_lock_per_m3,
      total_do_tagged,
      deposit_amount = 0,
      deposit_date,
      notes = '',
    } = body;

    // Validate required fields
    if (!customer_id || !price_lock_per_m3 || !total_do_tagged) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      );
    }

    // Insert deposit (code auto-generated by trigger)
    const { data: deposit, error: depositError } = await supabase
      .from('deposits')
      .insert({
        customer_id,
        price_lock_per_m3,
        total_do_tagged,
        deposit_amount: 0, // Will be updated by payment
        deposit_date,
        notes,
      })
      .select()
      .single();

    if (depositError) throw depositError;

    // If initial payment provided, create payment record
    if (deposit_amount > 0) {
      const { error: paymentError } = await supabase
        .from('deposit_payments')
        .insert({
          deposit_id: deposit.id,
          amount: deposit_amount,
          payment_method: 'Transfer',
          notes: 'Initial deposit',
        });

      if (paymentError) throw paymentError;
    }

    // Fetch complete deposit data
    const { data: completeDeposit, error: fetchError } = await supabase
      .from('v_deposits_summary')
      .select('*')
      .eq('id', deposit.id)
      .single();

    if (fetchError) throw fetchError;

    return NextResponse.json(completeDeposit);
  } catch (err: any) {
    console.error('CREATE DEPOSIT ERROR:', err);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}